import type { Metadata } from 'next';
import Header from '@/components/common/Header';
import FooterSection from '../homepage/components/FooterSection';
import ScanInterfaceInteractive from '../scan-interface/components/ScanInterfaceInteractive';
import Icon from '@/components/ui/AppIcon';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'AI Image Detector Online Free | Photo Forensics & Deepfake Tamper Check - TrustScan AI',
  description: 'Free online AI image detection and photo tamper tool. Detect synthetic images generated by Midjourney, Stable Diffusion, DALL-E, and FLUX, forged seals, and edited document photos using deep forensic heuristics.',
  alternates: {
    canonical: '/image-verification',
  },
  openGraph: {
    title: 'AI Image Detector Online Free | Photo Tamper & Deepfake Forensic Checker',
    description: 'Upload any image, certificate photo, or corporate seal to detect AI generation, Photoshop manipulation, and pixel tampering instantly.',
    url: 'https://www.trustscanai.in/image-verification',
    siteName: 'TrustScan AI',
    type: 'website',
  },
  keywords: [
    'ai image detector online',
    'ai image detector free',
    'check if image is ai generated',
    'fake image verification online',
    'photo manipulation detector',
    'fake stamp seal detector',
    'error level analysis online',
    'deepfake photo detector India',
    'stable diffusion detector',
    'midjourney image check',
    'TrustScan AI image forensic',
  ],
};

export default function ImageVerificationPage() {
  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How do you check if an image is AI generated or manipulated?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'TrustScan AI inspects high-frequency Fourier transform patterns, color quantization anomalies, and Error Level Analysis (ELA) to identify synthetic generation artifacts typical of diffusion models like Midjourney, FLUX, and DALL-E, as well as digital stamp/seal tampering.',
        },
      },
      {
        '@type': 'Question',
        name: 'Can this tool detect forged company stamps and signatures?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes. Fraudsters often copy blue ink seals from legitimate documents and paste them onto fake offer letters. TrustScan AI analyzes local compression gradients and edge anti-aliasing to spot pasted or manipulated digital seals.',
        },
      },
      {
        '@type': 'Question',
        name: 'Is the image verification tool free to use?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes, TrustScan AI provides free instant image forensics for students, citizens, and investigators with no credit card required.',
        },
      },
    ],
  };

  const capabilities = [
    {
      title: 'Diffusion Model Detection',
      desc: 'Detects microscopic noise distributions unique to generative diffusion architectures including FLUX.1, Midjourney v6, Stable Diffusion XL, and DALL-E 3.',
      icon: 'CpuChipIcon',
      badge: 'Multi-Model Heuristics',
    },
    {
      title: 'Forged Stamp & Seal Forensics',
      desc: 'Pinpoints copy-pasted corporate stamps, altered registrar seals, and recolored digital ink through Error Level Analysis (ELA) compression gradients.',
      icon: 'ShieldCheckIcon',
      badge: 'Seal Inspection',
    },
    {
      title: 'EXIF & Compression Artifacts',
      desc: 'Uncovers camera hardware fingerprint mismatches, missing sensor noise, and software signatures left by editing software like Photoshop and Canva.',
      icon: 'DocumentMagnifyingGlassIcon',
      badge: 'Metadata Audit',
    },
    {
      title: 'Fake Screenshot Analysis',
      desc: 'Detects font baseline shifts, altered numerals, and synthetic backgrounds in digital payment receipts, chat logs, and bank confirmation screenshots.',
      icon: 'DevicePhoneMobileIcon',
      badge: 'Receipt Audit',
    },
  ];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />

      {/* Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <main className="flex-grow pt-28 pb-16">
        <div className="container mx-auto px-4 max-w-7xl">
          
          {/* Hero Header */}
          <div className="text-center max-w-3xl mx-auto mb-10">
            <span className="text-xs font-mono font-bold tracking-wider uppercase px-3.5 py-1 rounded-full bg-primary/10 text-primary border border-primary/20 inline-block mb-3">
              Multi-Modal Forensic Vision
            </span>
            <h1 className="text-4xl md:text-5xl font-headline font-bold text-foreground mb-4 tracking-tight">
              AI Image & Photo Tamper Detector
            </h1>
            <p className="text-base md:text-lg text-muted-foreground leading-relaxed">
              Verify the authenticity of digital certificates, company seals, profile photographs, and screenshots. Inspect for synthetic AI generation, cloned layers, and pixel tampering.
            </p>
          </div>

          {/* Interactive Scanner Pre-Selected to 'image' */}
          <div className="mb-20">
            <ScanInterfaceInteractive initialScanType="image" />
          </div>

          {/* Technical Capabilities Grid */}
          <div className="max-w-5xl mx-auto mb-20">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-headline font-bold text-foreground mb-3">
                Comprehensive Visual Forensics Pipeline
              </h2>
              <p className="text-muted-foreground text-sm md:text-base">
                How TrustScan AI distinguishes genuine physical captures from synthetic AI renders and manipulated graphics.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {capabilities.map((item, idx) => (
                <div
                  key={idx}
                  className="bg-card border border-border rounded-2xl p-6 md:p-8 hover:border-primary/40 transition-colors shadow-subtle space-y-3"
                >
                  <div className="flex items-center justify-between">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center">
                      <Icon name={item.icon as any} size={22} />
                    </div>
                    <span className="text-xs font-mono font-bold text-primary px-2.5 py-0.5 rounded-full bg-primary/10 border border-primary/20">
                      {item.badge}
                    </span>
                  </div>
                  <h3 className="text-xl font-headline font-bold text-foreground">{item.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Educational Guide Section */}
          <div className="max-w-4xl mx-auto bg-muted/40 border border-border rounded-3xl p-8 md:p-12 mb-20 space-y-8">
            <div>
              <span className="text-xs font-mono font-bold text-primary uppercase tracking-wider">Technical Deep Dive</span>
              <h2 className="text-2xl md:text-3xl font-headline font-bold text-foreground mt-1 mb-4">
                How Error Level Analysis (ELA) Exposes Document Forgeries
              </h2>
              <p className="text-sm md:text-base text-muted-foreground leading-relaxed">
                When an image is saved in lossy formats like JPEG, each 8x8 block of pixels is compressed at a specific error rate. When a scammer opens a document image in an editor and pastes an altered company seal, date, or signature, that modified area is re-saved at a completely different compression generation. TrustScan AI computes the residual error difference to generate a forensic heatmap where altered areas immediately glow with high discrepancy.
              </p>
            </div>

            <div className="border-t border-border pt-6 grid grid-cols-1 sm:grid-cols-3 gap-4 text-center">
              <div className="p-4 rounded-xl bg-card border border-border">
                <div className="text-2xl font-bold font-mono text-primary mb-1">0.1s</div>
                <div className="text-xs text-muted-foreground">In-Memory Analysis</div>
              </div>
              <div className="p-4 rounded-xl bg-card border border-border">
                <div className="text-2xl font-bold font-mono text-emerald-500 mb-1">100%</div>
                <div className="text-xs text-muted-foreground">Private & Ephemeral</div>
              </div>
              <div className="p-4 rounded-xl bg-card border border-border">
                <div className="text-2xl font-bold font-mono text-purple-500 mb-1">Multi-Layer</div>
                <div className="text-xs text-muted-foreground">Frequency + Pixel Audit</div>
              </div>
            </div>
          </div>

          {/* FAQ Section */}
          <div className="max-w-4xl mx-auto mb-16">
            <h2 className="text-2xl font-headline font-bold text-foreground mb-6 text-center">
              Frequently Asked Questions About AI Image Verification
            </h2>
            <div className="space-y-4">
              {faqSchema.mainEntity.map((faq, idx) => (
                <div key={idx} className="bg-card border border-border rounded-2xl p-6 shadow-subtle">
                  <h3 className="text-lg font-headline font-bold text-foreground mb-2">{faq.name}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{faq.acceptedAnswer.text}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Cross-linking CTA */}
          <div className="text-center bg-card border border-border rounded-3xl p-8 max-w-4xl mx-auto">
            <h3 className="text-xl font-headline font-bold text-foreground mb-2">
              Verifying a Corporate Job Offer or Company Registration?
            </h3>
            <p className="text-sm text-muted-foreground mb-6">
              Check official 21-digit Corporate Identification Numbers (CIN) or inspect full multi-page PDF appointment letters.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Link
                href="/company-verification"
                className="px-6 py-2.5 bg-primary text-primary-foreground text-xs md:text-sm font-bold rounded-xl hover:opacity-90 transition-opacity"
              >
                Verify Company & CIN →
              </Link>
              <Link
                href="/scan-interface"
                className="px-6 py-2.5 bg-muted border border-border text-foreground text-xs md:text-sm font-semibold rounded-xl hover:bg-muted/80 transition-colors"
              >
                Offer Letter Scanner →
              </Link>
            </div>
          </div>

        </div>
      </main>

      <FooterSection />
    </div>
  );
}
