import type { Metadata } from 'next';
import Header from '@/components/common/Header';
import FooterSection from '../homepage/components/FooterSection';
import ScanInterfaceInteractive from '../scan-interface/components/ScanInterfaceInteractive';
import Icon from '@/components/ui/AppIcon';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Fake UPI Payment Screenshot Check Online | Paytm, GPay & UTR Forensics - TrustScan AI',
  description: 'Free online forensic checker for fake UPI payment screenshots. Detect altered rupee amounts, spoof payment APKs (Paytm, Google Pay, PhonePe), and 12-digit UTR transaction discrepancies instantly.',
  alternates: {
    canonical: '/payment-verification',
  },
  openGraph: {
    title: 'Fake UPI Payment Screenshot Check Online | UTR & Receipt Forensics',
    description: 'Upload suspicious UPI screenshots or transaction receipts to detect fake payment APKs, manipulated font typography, and invalid 12-digit UTR numbers.',
    url: 'https://www.trustscanai.in/payment-verification',
    siteName: 'TrustScan AI',
    type: 'website',
  },
  keywords: [
    'fake upi payment screenshot check',
    'fake upi screenshot detector',
    'fake paytm payment screenshot check online',
    'google pay fake receipt detector',
    '12 digit utr number verification',
    'fake payment receipt check online',
    'spoof paytm apk detector',
    'phonepe fake screenshot checker',
    'upi fraud forensics India',
    'TrustScan AI payment forensic',
  ],
};

export default function PaymentVerificationPage() {
  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How do scammers generate fake UPI payment screenshots?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Scammers frequently install fraudulent Android applications (often dubbed "Spoof Paytm" or "FakePay") that mimic the exact green/blue success animation of legitimate banking apps. They enter the merchant name and amount to generate a visually identical screenshot without transferring any money.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is a 12-digit UTR number in UPI transactions?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A Unique Transaction Reference (UTR) is a 12-digit sequential number generated by the National Payments Corporation of India (NPCI) for every successful IMPS and UPI transaction. The first 4 digits represent the Julian calendar date and year, which fake APK generators routinely get wrong.',
        },
      },
      {
        '@type': 'Question',
        name: 'How does TrustScan AI detect edited payment receipts?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'TrustScan AI analyzes font rasterization, character kerning, system status bar mismatches (such as iOS icons on an Android Paytm theme), and digital JPEG compression anomalies across the rupee amount field.',
        },
      },
    ],
  };

  const fraudSignals = [
    {
      title: 'Font Weight & Kerning Anomalies',
      desc: 'Genuine apps use licensed proprietary fonts (e.g. Google Sans, Paytm Bold). Fake APKs use generic Roboto or Arial with noticeable spacing discrepancies.',
      icon: 'DocumentTextIcon',
    },
    {
      title: 'Status Bar & Battery Icon Clash',
      desc: 'Scammers screenshot a template and edit text over it, often resulting in battery percentages or Wi-Fi icons that do not match the real device layout.',
      icon: 'DevicePhoneMobileIcon',
    },
    {
      title: '12-Digit NPCI UTR Algorithmic Check',
      desc: 'Verifies the mathematical and Julian date structure of the 12-digit reference number against NPCI banking standards.',
      icon: 'HashtagIcon',
    },
    {
      title: 'Pixel Discontinuity in Rupee Field',
      desc: 'Detects blurred compression blocks or mismatched white noise around the altered transaction amount (₹).',
      icon: 'EyeIcon',
    },
  ];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />

      {/* Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <main className="flex-grow pt-28 pb-16">
        <div className="container mx-auto px-4 max-w-7xl">
          
          {/* Hero Header */}
          <div className="text-center max-w-3xl mx-auto mb-10">
            <span className="text-xs font-mono font-bold tracking-wider uppercase px-3.5 py-1 rounded-full bg-primary/10 text-primary border border-primary/20 inline-block mb-3">
              UPI Transaction Forensics
            </span>
            <h1 className="text-4xl md:text-5xl font-headline font-bold text-foreground mb-4 tracking-tight">
              Fake UPI Screenshot & Receipt Detector
            </h1>
            <p className="text-base md:text-lg text-muted-foreground leading-relaxed">
              Verify screenshot authenticity for Google Pay, Paytm, and PhonePe. Inspect for fraudulent APK templates, altered rupee amounts, and fake 12-digit UTR reference numbers.
            </p>
          </div>

          {/* Interactive Scanner Pre-Selected to 'payment' */}
          <div className="mb-20">
            <ScanInterfaceInteractive initialScanType="payment" />
          </div>

          {/* Forensic Signals Breakdown */}
          <div className="max-w-5xl mx-auto mb-20">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-headline font-bold text-foreground mb-3">
                How Our Payment Forensics Engine Operates
              </h2>
              <p className="text-muted-foreground text-sm md:text-base">
                Detecting the 4 visual and cryptographic flaws left by fake payment APK generators.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {fraudSignals.map((item, idx) => (
                <div
                  key={idx}
                  className="bg-card border border-border rounded-2xl p-6 md:p-8 hover:border-primary/40 transition-colors shadow-subtle flex gap-5 items-start"
                >
                  <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0">
                    <Icon name={item.icon as any} size={24} />
                  </div>
                  <div className="space-y-1">
                    <h3 className="text-lg font-headline font-bold text-foreground">{item.title}</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Rule of Thumb Notice */}
          <div className="max-w-4xl mx-auto bg-amber-500/10 border border-amber-500/20 rounded-3xl p-8 mb-20 flex flex-col sm:flex-row gap-5 items-start">
            <div className="w-10 h-10 rounded-xl bg-amber-500/20 text-amber-500 flex items-center justify-center shrink-0 font-bold">
              <Icon name="ExclamationTriangleIcon" size={24} />
            </div>
            <div className="space-y-2">
              <h3 className="text-lg font-headline font-bold text-foreground">
                Golden Rule for Indian Shopkeepers & Merchants:
              </h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Never rely solely on a screenshot shown on a buyer&rsquo;s phone screen. Always wait for the official SMS notification from your issuing bank, confirm the credit inside your merchant app (PhonePe Business / Paytm for Business), or listen for your soundbox audio confirmation before handing over goods or services.
              </p>
            </div>
          </div>

          {/* FAQ Section */}
          <div className="max-w-4xl mx-auto mb-16">
            <h2 className="text-2xl font-headline font-bold text-foreground mb-6 text-center">
              Frequently Asked Questions About Fake UPI Detection
            </h2>
            <div className="space-y-4">
              {faqSchema.mainEntity.map((faq, idx) => (
                <div key={idx} className="bg-card border border-border rounded-2xl p-6 shadow-subtle">
                  <h3 className="text-lg font-headline font-bold text-foreground mb-2">{faq.name}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{faq.acceptedAnswer.text}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Cross-linking CTA */}
          <div className="text-center bg-card border border-border rounded-3xl p-8 max-w-4xl mx-auto">
            <h3 className="text-xl font-headline font-bold text-foreground mb-2">
              Verifying Job Offer Letters or Company Records?
            </h3>
            <p className="text-sm text-muted-foreground mb-6">
              Protect yourself against registration fee scams and counterfeit employment contracts.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Link
                href="/scan-interface"
                className="px-6 py-2.5 bg-primary text-primary-foreground text-xs md:text-sm font-bold rounded-xl hover:opacity-90 transition-opacity"
              >
                Scan Offer Letter →
              </Link>
              <Link
                href="/company-verification"
                className="px-6 py-2.5 bg-muted border border-border text-foreground text-xs md:text-sm font-semibold rounded-xl hover:bg-muted/80 transition-colors"
              >
                Verify Company & CIN →
              </Link>
            </div>
          </div>

        </div>
      </main>

      <FooterSection />
    </div>
  );
}
