import Header from '@/components/common/Header';
import FooterSection from '../homepage/components/FooterSection';
import Icon from '@/components/ui/AppIcon';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Legal Disclaimer | TrustScan AI',
  description: 'Important legal notices about the use of TrustScan AI fraud detection results. TrustScan AI results are informational and should not be treated as definitive legal or financial advice.',
  alternates: {
    canonical: '/disclaimer',
  },
  robots: { index: true, follow: true },
};

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      <main className="flex-grow pt-32 pb-16">
        <div className="container mx-auto px-4 max-w-4xl">
          <div className="mb-12">
            <h1 className="text-4xl md:text-5xl font-headline font-bold text-foreground mb-4">
              Legal Disclaimer
            </h1>
            <p className="text-muted-foreground flex items-center gap-2">
              <Icon name="CalendarIcon" size={16} />
              Last updated: September 13, 2026
            </p>
          </div>

          <div className="bg-card border border-border rounded-3xl p-8 md:p-12 space-y-12 shadow-subtle">

            {/* Important notice banner */}
            <div className="bg-amber-500/10 border border-amber-500/30 rounded-2xl p-6 flex gap-4">
              <div className="text-amber-500 flex-shrink-0 mt-1">
                <Icon name="ExclamationTriangleIcon" size={24} />
              </div>
              <div>
                <h2 className="font-headline font-bold text-foreground mb-2">Important Notice</h2>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  TrustScan AI provides AI-powered analysis tools for informational purposes only.
                  Our scan results should be used as a guide to assist your judgment — they are not
                  a substitute for professional legal, financial, or law enforcement advice.
                </p>
              </div>
            </div>

            <section>
              <h2 className="text-2xl font-headline font-bold text-foreground mb-4">
                1. Nature of the Service
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                TrustScan AI (&ldquo;the Service&rdquo;) is an artificial intelligence-powered
                platform that analyzes documents, images, URLs, SMS messages, and business
                identifiers to detect potential fraud indicators. The Service is operated by
                Shubham Dubey, an independent software developer based in Navi Mumbai, Maharashtra,
                India (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;TrustScan AI&rdquo;).
              </p>
              <p className="text-muted-foreground leading-relaxed">
                TrustScan AI uses machine learning models, LLM reasoning, digital forensics
                techniques, and rule-based heuristics to assess the likelihood of fraud. These
                methods, while advanced, are probabilistic in nature and subject to limitations.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-headline font-bold text-foreground mb-4">
                2. No Guarantee of Accuracy
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                The results generated by TrustScan AI are{' '}
                <strong className="text-foreground">not guaranteed to be accurate, complete, or current.</strong>{' '}
                Artificial intelligence systems, including those used by TrustScan AI, can produce
                incorrect results, including both false positives (flagging legitimate content as
                fraudulent) and false negatives (failing to detect actual fraud).
              </p>
              <p className="text-muted-foreground leading-relaxed">
                You should independently verify any scan result before making decisions based on it.
                TrustScan AI scan results should be treated as one data point among many — not as a
                final verdict.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-headline font-bold text-foreground mb-4">
                3. Not Legal or Financial Advice
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Nothing on TrustScan AI constitutes legal, financial, regulatory, or professional
                advice of any kind. The Service does not create any professional-client relationship
                between you and TrustScan AI.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                If you have reason to believe you are a victim of fraud, identity theft, or a
                financial crime, you should:
              </p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground mt-4 ml-2">
                <li>Report the matter to your local police or cybercrime cell</li>
                <li>File a complaint at the National Cyber Crime Reporting Portal (cybercrime.gov.in)</li>
                <li>Contact your bank or financial institution immediately</li>
                <li>Seek advice from a qualified legal professional</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-headline font-bold text-foreground mb-4">
                4. Company Verification Disclaimer
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                TrustScan AI&apos;s company verification feature queries the Ministry of Corporate
                Affairs (MCA) registry and related databases. The information displayed reflects
                data available at the time of the query and may not reflect the most current
                registration status. A company appearing as &ldquo;registered&rdquo; in our results
                does not guarantee that the company is legitimate, currently operational, or not
                engaged in fraudulent activity. Always cross-verify with official government portals
                at{' '}
                <a
                  href="https://www.mca.gov.in"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary hover:underline"
                >
                  www.mca.gov.in
                </a>.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-headline font-bold text-foreground mb-4">
                5. Limitation of Liability
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                To the fullest extent permitted by applicable law, TrustScan AI, its operators,
                developers, and affiliates shall not be liable for any direct, indirect, incidental,
                consequential, special, or exemplary damages arising from:
              </p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-2">
                <li>Your use of or reliance on TrustScan AI scan results</li>
                <li>Any incorrect, incomplete, or outdated scan result</li>
                <li>Any decision made based on TrustScan AI results</li>
                <li>Interruption or unavailability of the Service</li>
                <li>Unauthorized access to or alteration of your data</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed mt-4">
                This limitation of liability applies regardless of whether the claim is based on
                warranty, contract, tort, or any other legal theory.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-headline font-bold text-foreground mb-4">
                6. User Responsibility
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                By using TrustScan AI, you acknowledge that:
              </p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground mt-4 ml-2">
                <li>You use the Service at your own risk and discretion</li>
                <li>You will not upload documents containing other people&apos;s personal information without their consent</li>
                <li>You will not use TrustScan AI results to defame, harass, or harm any individual or organization</li>
                <li>You accept that scan results are probabilistic assessments, not definitive conclusions</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-headline font-bold text-foreground mb-4">
                7. Intellectual Property
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                All content on TrustScan AI — including but not limited to the platform design,
                codebase, analysis logic, branding, and written content — is the intellectual
                property of Shubham Dubey / TrustScan AI. Unauthorized reproduction, distribution,
                or commercial use of any content is strictly prohibited.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-headline font-bold text-foreground mb-4">
                8. Governing Law
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                This Disclaimer is governed by and construed in accordance with the laws of India,
                specifically the Information Technology Act, 2000 and the Digital Personal Data
                Protection Act, 2023. Any disputes arising from the use of TrustScan AI shall be
                subject to the exclusive jurisdiction of the courts of Maharashtra, India.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-headline font-bold text-foreground mb-4">
                9. Contact Us
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                If you have questions about this disclaimer or believe a scan result has caused
                harm, please contact us:
              </p>
              <div className="space-y-2 text-muted-foreground">
                <p>
                  <strong className="text-foreground">Email:</strong>{' '}
                  <a href="mailto:trustscan.ai@gmail.com" className="text-primary hover:underline">
                    trustscan.ai@gmail.com
                  </a>
                </p>
                <p>
                  <strong className="text-foreground">Phone:</strong>{' '}
                  <a href="tel:+918591694920" className="text-primary hover:underline">
                    +91 85916 94920
                  </a>
                </p>
                <p>
                  <strong className="text-foreground">Address:</strong> Navi Mumbai, Maharashtra, India
                </p>
              </div>
            </section>

          </div>
        </div>
      </main>
      <FooterSection />
    </div>
  );
}
